In [1]:
from stock_env import StockEnv
import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2

In [2]:
env_args = {
    "asset_codes": ['AAPL', 'V', 'BABA', 'ADBE', 'SNE'],
    "features": ["close", "high", "low"],
    "start_date": "2017-12-12",
    "end_date": "2017-12-16", 
    "window_len": 1,
    "data_path": "AmericaStock.csv"
}

In [3]:
stock_env = StockEnv(**env_args)

In [4]:
stock_env.asset_dict["AAPL"]

close      high       low
2017-12-12  0.986952  0.990918  0.985572
2017-12-13  0.990228  0.997528  0.988676
2017-12-14  0.989941  0.995172  0.986664
2017-12-15  1.000000  1.001150  0.991320
2017-12-16  1.000000  1.000000  1.000000

In [5]:
stock_env.asset_dict["V"]

close      high       low
2017-12-12  0.996837  0.999209  0.984010
2017-12-13  0.995519  1.004832  0.994465
2017-12-14  0.992093  1.002372  0.992093
2017-12-15  1.000000  1.003339  0.987436
2017-12-16  1.000000  1.000000  1.000000

In [6]:
stock_env.price_change_ratios

array([[1.        , 1.00331974, 0.99867795, 1.0104787 , 1.0248638 ,
        1.00044813],
       [1.        , 0.99970976, 0.99655811, 0.97325324, 0.98965108,
        0.99552072],
       [1.        , 1.01016142, 1.00797024, 1.01048035, 1.01434286,
        1.0087739 ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]])

In [7]:
# stock_env.states

In [8]:
state0 = stock_env.reset()

In [9]:
state0

array([[[1.        , 1.00114962, 0.99132034]],

       [[1.        , 1.0033386 , 0.9874363 ]],

       [[1.        , 1.        , 0.9795448 ]],

       [[1.        , 1.01391471, 0.98191651]],

       [[1.        , 1.00334523, 0.99375558]]])

In [10]:
stock_env.render()

We are at date 2017-12-12
allocation of portfolio at the end of prev date: [1. 0. 0. 0. 0. 0.]


In [11]:
action0 = np.array([0, 1, 0, 0, 0, 0])
action1 = np.array([0, 0, 1, 0, 0, 0])
action2 = np.array([0, 0, 1, 0, 0, 0])

In [12]:
state0 = stock_env.reset()
reward, done, next_state = stock_env.step(action0)

In [73]:
stock_env.t

1

In [13]:
print(f"##########Reward################\n{reward}\nnext state \n{next_state} \ndone \n{done}")

##########Reward################
0.000819407932685385
next state 
[[[0.9902282  0.99752831 0.98867621]]

 [[0.99551924 1.00483219 0.99446494]]

 [[1.01682512 1.02391242 1.00432152]]

 [[0.99616923 0.99949299 0.97622669]]

 [[0.99576271 0.99732382 0.99308653]]] 
done 
False


In [14]:
reward, done, next_state = stock_env.step(action1)

In [15]:
stock_env.t

2

In [16]:
print(f"##########Reward################\n{reward}\nnext state \n{next_state} \ndone \n{done}")

##########Reward################
-0.0059596083344041475
next state 
[[[0.98994079 0.99517158 0.98666437]]

 [[0.99209278 1.00237217 0.99209278]]

 [[0.98962835 0.99907808 0.97729761]]

 [[0.98585995 1.00681652 0.98574728]]

 [[0.99130241 0.99776985 0.99130241]]] 
done 
False


In [17]:
reward, done, next_state = stock_env.step(action2)

In [18]:
print(f"##########Reward################\n{reward}\nnext state \n{next_state} \ndone \n{done}")

##########Reward################
0.00545533697402526
next state 
[[[1.         1.00114962 0.99132034]]

 [[1.         1.0033386  0.9874363 ]]

 [[1.         1.         0.9795448 ]]

 [[1.         1.01391471 0.98191651]]

 [[1.         1.00334523 0.99375558]]] 
done 
False


In [19]:
stock_env.t

3