In [1]:
from stock_env import StockEnv
import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2

In [45]:
env_args = {
    "asset_codes": ['AAPL', 'V', 'BABA', 'ADBE', 'SNE'],
    "features": ["close", "high", "low"],
    "start_date": "2017-12-12",
    "end_date": "2017-12-16", 
    "window_len": 1,
    "data_path": "AmericaStock.csv"
}

In [46]:
stock_env = StockEnv(**env_args)

In [47]:
# print(len(stock_env.states))
print(stock_env.states)

[array([[[[0.98695177, 0.990918  , 0.9855722 ]],

        [[0.99683714, 0.9992093 , 0.98400986]],

        [[1.0062807 , 1.0265629 , 1.0012677 ]],

        [[0.97200155, 0.9809588 , 0.9601149 ]],

        [[0.9953167 , 0.99754685, 0.9895183 ]]]], dtype=float32), array([[[[0.9902282 , 0.9975283 , 0.9886762 ]],

        [[0.9955192 , 1.0048321 , 0.99446493]],

        [[1.0168251 , 1.0239124 , 1.0043216 ]],

        [[0.9961692 , 0.999493  , 0.9762267 ]],

        [[0.9957627 , 0.9973238 , 0.9930865 ]]]], dtype=float32), array([[[[0.9899408 , 0.9951716 , 0.98666435]],

        [[0.9920928 , 1.0023721 , 0.9920928 ]],

        [[0.9896284 , 0.9990781 , 0.9772976 ]],

        [[0.98585993, 1.0068165 , 0.9857473 ]],

        [[0.99130243, 0.99776983, 0.99130243]]]], dtype=float32), array([[[[1.       , 1.0011497, 0.9913204]],

        [[1.       , 1.0033386, 0.9874363]],

        [[1.       , 1.       , 0.9795448]],

        [[1.       , 1.0139147, 0.9819165]],

        [[1.       , 1.003345

In [48]:
stock_env.asset_dict["AAPL"]

close      high       low
2017-12-12  0.986952  0.990918  0.985572
2017-12-13  0.990228  0.997528  0.988676
2017-12-14  0.989941  0.995172  0.986664
2017-12-15  1.000000  1.001150  0.991320
2017-12-16  1.000000  1.000000  1.000000

In [49]:
stock_env.asset_dict["V"]

close      high       low
2017-12-12  0.996837  0.999209  0.984010
2017-12-13  0.995519  1.004832  0.994465
2017-12-14  0.992093  1.002372  0.992093
2017-12-15  1.000000  1.003339  0.987436
2017-12-16  1.000000  1.000000  1.000000

In [50]:
stock_env.price_change_ratios

array([[1.        , 1.0033197 , 0.99867797, 1.0104787 , 1.0248638 ,
        1.0004481 ],
       [1.        , 0.9997098 , 0.9965581 , 0.97325325, 0.9896511 ,
        0.9955207 ],
       [1.        , 1.0101614 , 1.0079702 , 1.0104804 , 1.0143429 ,
        1.0087739 ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]], dtype=float32)

In [51]:
stock_env.states

[array([[[[0.98695177, 0.990918  , 0.9855722 ]],
 
         [[0.99683714, 0.9992093 , 0.98400986]],
 
         [[1.0062807 , 1.0265629 , 1.0012677 ]],
 
         [[0.97200155, 0.9809588 , 0.9601149 ]],
 
         [[0.9953167 , 0.99754685, 0.9895183 ]]]], dtype=float32),
 array([[[[0.9902282 , 0.9975283 , 0.9886762 ]],
 
         [[0.9955192 , 1.0048321 , 0.99446493]],
 
         [[1.0168251 , 1.0239124 , 1.0043216 ]],
 
         [[0.9961692 , 0.999493  , 0.9762267 ]],
 
         [[0.9957627 , 0.9973238 , 0.9930865 ]]]], dtype=float32),
 array([[[[0.9899408 , 0.9951716 , 0.98666435]],
 
         [[0.9920928 , 1.0023721 , 0.9920928 ]],
 
         [[0.9896284 , 0.9990781 , 0.9772976 ]],
 
         [[0.98585993, 1.0068165 , 0.9857473 ]],
 
         [[0.99130243, 0.99776983, 0.99130243]]]], dtype=float32),
 array([[[[1.       , 1.0011497, 0.9913204]],
 
         [[1.       , 1.0033386, 0.9874363]],
 
         [[1.       , 1.       , 0.9795448]],
 
         [[1.       , 1.0139147, 0.9819165]

In [52]:
state0 = stock_env.reset()

In [53]:
state0

array([[[[0.98695177, 0.990918  , 0.9855722 ]],

        [[0.99683714, 0.9992093 , 0.98400986]],

        [[1.0062807 , 1.0265629 , 1.0012677 ]],

        [[0.97200155, 0.9809588 , 0.9601149 ]],

        [[0.9953167 , 0.99754685, 0.9895183 ]]]], dtype=float32)

In [54]:
stock_env.render()

We are at date 2017-12-12
allocation of portfolio at the end of prev date: [1. 0. 0. 0. 0. 0.]


In [55]:
action = np.array([0, 1, 0, 0, 0, 0], dtype="float32")
action

array([0., 1., 0., 0., 0., 0.], dtype=float32)

In [62]:
done = False
step = 0
stock_env.reset()
while done is False:
    print(f' ------------------------ step {step}----------------------------')
    print(f'Time step before taking action: {stock_env.t}')
    reward, done, nxt_state = stock_env.step(action)
    print(nxt_state)
    print(f'receive reward: {reward}')
    print(f"done: {done}")
    step += 1


 ------------------------ step 0----------------------------
Time step before taking action: 0
stock price change after the action: [1.         1.0033197  0.99867797 1.0104787  1.0248638  1.0004481 ]
transaction cost: 0.0025
test: 1.0033197402954102 
reward before log: 1.0008197402954102
[[[[0.9902282  0.9975283  0.9886762 ]]

  [[0.9955192  1.0048321  0.99446493]]

  [[1.0168251  1.0239124  1.0043216 ]]

  [[0.9961692  0.999493   0.9762267 ]]

  [[0.9957627  0.9973238  0.9930865 ]]]]
receive reward: 0.0008194044918361998
done: False
 ------------------------ step 1----------------------------
Time step before taking action: 1
stock price change after the action: [1.         0.9997098  0.9965581  0.97325325 0.9896511  0.9955207 ]
transaction cost: 0.0025
test: 0.9997097849845886 
reward before log: 0.9972097849845887
[[[[0.9899408  0.9951716  0.98666435]]

  [[0.9920928  1.0023721  0.9920928 ]]

  [[0.9896284  0.9990781  0.9772976 ]]

  [[0.98585993 1.0068165  0.9857473 ]]

  [[0.99130

In [61]:
np.log(1.0008197402954102)

0.0008194044918361998