In [1]:
import pandas as pd

%load_ext autoreload
%autoreload 2

In [2]:
df = pd.read_csv('AmericaStock.csv')

In [3]:
df.head()

time   close    open    high     low  volume percent  code
0  Jan 05, 2015  106.25  108.29  108.65  105.41  64.29M  -2.82%  AAPL
1  Jan 06, 2015  106.26  106.54  107.43  104.63  65.80M   0.01%  AAPL
2  Jan 07, 2015  107.75  107.20  108.20  106.69  40.11M   1.40%  AAPL
3  Jan 08, 2015  111.89  109.23  112.15  108.70  59.36M   3.84%  AAPL
4  Jan 09, 2015  112.01  112.67  113.25  110.21  53.70M   0.11%  AAPL

In [4]:
df['code'].unique()

array(['AAPL', 'V', 'BABA', 'ADBE', 'SNE'], dtype=object)

In [5]:
codes = ['AAPL', 'BABA']

In [6]:
df[df['code'].isin(codes)]

time   close    open    high     low  volume percent  code
0     Jan 05, 2015  106.25  108.29  108.65  105.41  64.29M  -2.82%  AAPL
1     Jan 06, 2015  106.26  106.54  107.43  104.63  65.80M   0.01%  AAPL
2     Jan 07, 2015  107.75  107.20  108.20  106.69  40.11M   1.40%  AAPL
3     Jan 08, 2015  111.89  109.23  112.15  108.70  59.36M   3.84%  AAPL
4     Jan 09, 2015  112.01  112.67  113.25  110.21  53.70M   0.11%  AAPL
...            ...     ...     ...     ...     ...     ...     ...   ...
2258  Dec 22, 2017  176.29  175.84  176.66  175.04  12.52M   0.55%  BABA
2259  Dec 26, 2017  172.33  174.55  175.15  171.73  12.91M  -2.25%  BABA
2260  Dec 27, 2017  172.97  172.29  173.87  171.73  10.15M   0.37%  BABA
2261  Dec 28, 2017  172.30  173.04  173.53  171.67   9.51M  -0.39%  BABA
2262  Dec 29, 2017  172.43  172.28  173.67  171.20   9.70M   0.08%  BABA

[1509 rows x 8 columns]

In [7]:
selected_data = df[df['code'].isin(codes)]

In [8]:
for code in codes:
    asset_data_len = len(df[df['code'] == code])
    print(f'avaiable data for code {code}: {asset_data_len}')

avaiable data for code AAPL: 755
avaiable data for code BABA: 754


In [9]:
codes = ['AAPL', 'V', 'BABA', 'ADBE', 'SNE']
for code in codes:
    asset_data_len = len(df[df['code'] == code])
    print(f'avaiable data for code {code}: {asset_data_len}')

avaiable data for code AAPL: 755
avaiable data for code V: 754
avaiable data for code BABA: 754
avaiable data for code ADBE: 755
avaiable data for code SNE: 754


In [10]:
df[df['code'] == 'BABA'].index

Int64Index([1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518,
            ...
            2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262],
           dtype='int64', length=754)

In [11]:
china_df = pd.read_csv('ChinaStock.csv')

In [12]:
china_codes = china_df['code'].unique()
china_codes

array([600000, 600326, 600662, 600679, 600698, 600821, 600876, 600962,
            2,     11,     48,    151,    725,    862,    985,   2066],
      dtype=int64)

In [13]:
china_df.index

RangeIndex(start=0, stop=42246, step=1)

In [14]:
df = pd.read_csv('AmericaStock.csv', index_col=0, parse_dates=True)

In [15]:
df

close    open    high     low   volume percent  code
time                                                             
2015-01-05  106.25  108.29  108.65  105.41   64.29M  -2.82%  AAPL
2015-01-06  106.26  106.54  107.43  104.63   65.80M   0.01%  AAPL
2015-01-07  107.75  107.20  108.20  106.69   40.11M   1.40%  AAPL
2015-01-08  111.89  109.23  112.15  108.70   59.36M   3.84%  AAPL
2015-01-09  112.01  112.67  113.25  110.21   53.70M   0.11%  AAPL
...            ...     ...     ...     ...      ...     ...   ...
2017-12-22   45.68   45.73   45.78   45.44  453.37K   0.59%   SNE
2017-12-26   45.21   45.34   45.46   45.13  584.26K  -1.03%   SNE
2017-12-27   45.26   45.20   45.27   45.07  386.53K   0.11%   SNE
2017-12-28   45.29   45.30   45.42   45.17  541.48K   0.07%   SNE
2017-12-29   44.95   45.29   45.29   44.95  435.67K  -0.75%   SNE

[3772 rows x 7 columns]

In [16]:
df.loc['2017-12-22': '2017-12-26'].sort_index()

close    open    high     low   volume percent  code
time                                                             
2017-12-22  175.01  174.68  175.42  174.50   16.35M   0.00%  AAPL
2017-12-22  112.69  112.39  113.11  112.25    6.19M   0.25%     V
2017-12-22  176.29  175.84  176.66  175.04   12.52M   0.55%  BABA
2017-12-22  175.00  173.99  175.10  173.75    1.70M   0.25%  ADBE
2017-12-22   45.68   45.73   45.78   45.44  453.37K   0.59%   SNE
2017-12-26  170.57  170.80  171.47  169.68   33.19M  -2.54%  AAPL
2017-12-26  112.99  112.07  113.44  112.07    3.95M   0.27%     V
2017-12-26  172.33  174.55  175.15  171.73   12.91M  -2.25%  BABA
2017-12-26  174.44  174.36  175.00  173.03  918.36K  -0.32%  ADBE
2017-12-26   45.21   45.34   45.46   45.13  584.26K  -1.03%   SNE

In [17]:
date_range = pd.date_range('2017-12-22', '2017-12-26')
date_range

DatetimeIndex(['2017-12-22', '2017-12-23', '2017-12-24', '2017-12-25',
               '2017-12-26'],
              dtype='datetime64[ns]', freq='D')

In [18]:
asset_data = df[df['code'] == 'AAPL'].loc['2017-12-22': '2017-12-26'].reindex(date_range)

In [19]:
asset_data

close    open    high     low  volume percent  code
2017-12-22  175.01  174.68  175.42  174.50  16.35M   0.00%  AAPL
2017-12-23     NaN     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-24     NaN     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-25     NaN     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-26  170.57  170.80  171.47  169.68  33.19M  -2.54%  AAPL

In [20]:
asset_data['close'].fillna(method='pad', inplace=True)

In [21]:
asset_data

close    open    high     low  volume percent  code
2017-12-22  175.01  174.68  175.42  174.50  16.35M   0.00%  AAPL
2017-12-23  175.01     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-24  175.01     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-25  175.01     NaN     NaN     NaN     NaN     NaN   NaN
2017-12-26  170.57  170.80  171.47  169.68  33.19M  -2.54%  AAPL

In [22]:
asset_data.fillna({'high': asset_data['close'], 'open':asset_data['close'], 'low': asset_data['close']}, inplace=True)

In [23]:
asset_data

close    open    high     low  volume percent  code
2017-12-22  175.01  174.68  175.42  174.50  16.35M   0.00%  AAPL
2017-12-23  175.01  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-24  175.01  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-25  175.01  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-26  170.57  170.80  171.47  169.68  33.19M  -2.54%  AAPL

In [24]:
base_price = asset_data['close'][-1]

In [25]:
asset_data['close'] /= base_price

In [26]:
asset_data

close    open    high     low  volume percent  code
2017-12-22  1.02603  174.68  175.42  174.50  16.35M   0.00%  AAPL
2017-12-23  1.02603  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-24  1.02603  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-25  1.02603  175.01  175.01  175.01     NaN     NaN   NaN
2017-12-26  1.00000  170.80  171.47  169.68  33.19M  -2.54%  AAPL

In [27]:
asset_data['close'][1: 2].to_numpy()

array([1.02603037])

In [28]:
import numpy as np

In [29]:
v_close = np.ones(2)

In [30]:
from datetime import datetime

In [31]:
d1 = datetime.strptime("2002-12-10", "%Y-%m-%d")
d2 = datetime.strptime("2002-12-11", "%Y-%m-%d")
(d2 - d1).days

1

In [32]:
from stock_env import StockEnv

In [35]:
env_args = {
    "asset_codes": ['AAPL', 'V', 'BABA', 'ADBE', 'SNE'],
    "features": ["close", "open", "high", "low"],
    "start_date": "2017-12-12",
    "end_date": "2017-12-16", 
    "window_len": 2,
    "data_path": "AmericaStock.csv"
}

In [1]:
stock_env = StockEnv(**env_args)

NameError: name 'StockEnv' is not defined

In [38]:
asset_dict = stock_env.clean_raw_data("AmericaStock.csv")

In [39]:
asset_dict["AAPL"]

close      open      high       low
2017-12-12  0.986952  0.989538  0.990918  0.985572
2017-12-13  0.990228  0.991550  0.997528  0.988676
2017-12-14  0.989941  0.990975  0.995172  0.986664
2017-12-15  1.000000  0.998046  1.001150  0.991320
2017-12-16  1.000000  1.000000  1.000000  1.000000

In [40]:
asset_dict["V"]

close      open      high       low
2017-12-12  0.996837  0.987261  0.999209  0.984010
2017-12-13  0.995519  0.999385  1.004832  0.994465
2017-12-14  0.992093  0.997628  1.002372  0.992093
2017-12-15  1.000000  1.001318  1.003339  0.987436
2017-12-16  1.000000  1.000000  1.000000  1.000000

In [41]:
asset_dict["AAPL"].iloc[1]["close"]

0.9902282002644135

In [42]:
price_change_ratios = stock_env.get_price_change_ratios(asset_dict)

In [43]:
price_change_ratios

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [1.        , 1.00331974, 0.99867795, 1.0104787 , 1.0248638 ,
        1.00044813],
       [1.        , 0.99970976, 0.99655811, 0.97325324, 0.98965108,
        0.99552072],
       [1.        , 1.01016142, 1.00797024, 1.01048035, 1.01434286,
        1.0087739 ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]])

In [44]:
states = stock_env.get_states(asset_dict)